### ISSUE TITLE
screenshots are missing

### ISSUE THREAD

**Issue by smmoosavi** [h-ayat/my-vim#1]
please add screenshots

**Comment by h-ayat** [comment]
![out](https://user-images.githubusercontent.com/4332421/65906169-deaa9480-e3ce-11e9-8ef3-2355876f1fb3.gif)

**Comment by h-ayat** [comment]
Thanx for pointing out

**Comment by h-ayat** [comment]
![out](https://user-images.githubusercontent.com/4332421/65906751-f2a2c600-e3cf-11e9-9e52-8a498c19f193.gif)
